
  #   # Setting class is redundant, but adds autocompletions for the IDE.
  #   class: Ws\AcmeBundle\Controller\AcmeController
  #   arguments:
  #   # Add this tag to inject services into controller actions.
  #   tags: ['controller.service_arguments'] 
  #   # Call the setContainer method to get access to the services via
  #   # $this->get() method.
  #   calls:
  #       - ['setContainer', ['@service_container']]
services:
  Ws\AcmeBundle\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    calls:
        - ['setContainer', ['@service_container']]